version: '2'

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./:/app
      - ${PWD}/boomer.conf:/etc/nginx/conf.d
    links:
      - php
    depends_on:
      - php
  php:
    build: .
    volumes:
      - ./:/app
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=boompguser
      - POSTGRES_PASSWORD=BoomR@2020
      - POSTGRES_DB=boomer_db
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"
